var express = require('express');
var app = express();
var bodyParser = require('body-parser')

var files = [
	{
		id: "autogeneratedid",
		filename: "pusty dokument.txt",
		data: "",
		folder: "/home/data/example"
	}
];

app.use(express.static('public'));
app.use(bodyParser.json({limit: '50mb'}));

app.get('/search/:word', function(req, res) {
    var s = '<p>Szukam: ' + req.params.word + '</p>';
    res.send(s);
});

app.get('/file/:id', function(req, res) {
	var id = req.params.id;

	var f = null;    
	for (i=0; i < files.length; i++ ) {
		if (files[i].id == id) {
			f = files[i];
			break;
		}
	}
	if (f == null) {
		res.type("text/plain");
		res.send("Nie mogę odnaleźć pliku o id: " + id);
	} else {
    	res.json(f);
    }
});

app.get('/files', function(req, res) {
	var id = req.params.id;
	var f = [];

	for (i=0; i < files.length; i++ ) {
		var tmp = {
			id: files[i].id,
			name: files[i].filename
		}
		f.push(tmp);
	}

	res.json(f);
});

var id = 1;

app.post('/push', function(req, res) {
	console.log(req.body);
	id++;
	file = {
		id: id,
		filename: req.body.filename,
		data: req.body.data,
		folder: "/home/data/example"
	};
	files.push(file);
	var s = '<p>OK</p>';
	res.send(s);
});


app.listen(process.env.PORT || 4730);